# Generated by Django 2.2.7 on 2019-12-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='answer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Answer'),
        ),
        migrations.AlterField(
            model_name='approved',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Question'),
        ),
    ]
