# Generated by Django 2.2.7 on 2019-12-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_auto_20191208_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Answer'),
        ),
    ]
